import { Component, OnInit } from '@angular/core';
import { PageEvent, MatDialog } from '@angular/material';
import { ContactDialogComponent } from './contact-dialog/contact-dialog.component';
import { FormControl } from '@angular/forms';
import { DeleteConfirmDialogComponent } from 'src/app/shared/delete-confirm-dialog/delete-confirm-dialog.component';

@Component({
  selector: 'app-contact-screen',
  templateUrl: './contact-screen.component.html',
  styleUrls: ['./contact-screen.component.scss']
})
export class ContactScreenComponent implements OnInit {

  pageEvent: PageEvent;
  public pageSize = 10;
  public currentPage = 0;
  public totalSize = 0;
  filterToggle = false;
  status = [{'status_id':'1','status_name':'Active'},
           {'status_id':'2','status_name':'Inactive'}]

  public status_filter = ""; 
  contactName = new FormControl();
  clientName = new FormControl();
  jobTitle = new FormControl();
  contactNumber = new FormControl();
  statu = new FormControl();
  public popoverStatusTitle: string = 'Confirm Status Change';
  public popoverStatusMessage: string = 'Are you sure you want to change status?';
  public cancelClicked: boolean = false;

  allContacts = [
  { activityDate: null,
  clientID: 3402,
  clientName: "thinc design",
  contactAddressID: null,
  contactCity: "Toronto",
  contactCountry: "Canada",
  contactCountryID: 1,
  contactEmail: "mtocher@thincdesign.ca",
  contactID: 5939,
  contactIsBillingContact: null,
  contactIsPrimaryContact: null,
  contactJobTitle: "Partner",
  contactMuncipality: null,
  contactMuncipalityID: null,
  contactName: "Mike Tocher",
  contactPhone: "416-236-3335",
  contactState: "Ontario",
  contactStateID: 7,
  contactStreetAddress: "171 East Liberty Street, Unit 266",
  contactZip: "M6K 3P6",
  contactbtDelete: null,
  contactbtStatus: true,
  createdBy: null,
  createdDate: "2020-07-13T09:03:44.47",
  ext: "302",
  isAddressCopiedFromClient: true,
  modifiedBy: null,
  modifiedDate: null,
  quotesCount: 1,
  totalContacts: 1408 },
  {
  activityDate: null,
  clientID: 3271,
  clientName: "Rohnbrad Inc.",
  contactAddressID: null,
  contactCity: "Guleph",
  contactCountry: "Canada",
  contactCountryID: 1,
  contactEmail: "johanna@ftarchitects.ca",
  contactID: 5335,
  contactIsBillingContact: null,
  contactIsPrimaryContact: null,
  contactJobTitle: "NA",
  contactMuncipality: null,
  contactMuncipalityID: null,
  contactName: "Bob Ireland",
  contactPhone: "000-000-0000",
  contactState: "Ontario",
  contactStateID: 7,
  contactStreetAddress: "174 Wyndham Street North, Suite 303",
  contactZip: "N1H 6R7",
  contactbtDelete: null,
  contactbtStatus: true,
  createdBy: null,
  createdDate: "2020-06-25T15:41:37.053",
  ext: "-",
  isAddressCopiedFromClient: true,
  modifiedBy: null,
  modifiedDate: null,
  quotesCount: 1,
  totalContacts: 1408 },
  {
  activityDate: null,
  clientID: 3237,
  clientName: "Northfield Development Corporation ",
  contactAddressID: null,
  contactCity: "NA",
  contactCountry: "Canada",
  contactCountryID: 1,
  contactEmail: "ashley@baxterengineering.ca",
  contactID: 5604,
  contactIsBillingContact: false,
  contactIsPrimaryContact: false,
  contactJobTitle: "NA",
  contactMuncipality: null,
  contactMuncipalityID: null,
  contactName: "Ashley Baxter ",
  contactPhone: "613-243-3166",
  contactState: "Ontario",
  contactStateID: 7,
  contactStreetAddress: "NA",
  contactZip: "NA",
  contactbtDelete: null,
  contactbtStatus: true,
  createdBy: null,
  createdDate: "2020-07-03T13:04:26.65",
  ext: "-",
  isAddressCopiedFromClient: false,
  modifiedBy: null,
  modifiedDate: null,
  quotesCount: 1,
  totalContacts: 1408 },
  {
  activityDate: null,
  clientID: 3230,
  clientName: "Ledcor Construction Limited",
  contactAddressID: null,
  contactCity: "Toronto",
  contactCountry: "Canada",
  contactCountryID: 1,
  contactEmail: "jessica.allin@ledcor.com",
  contactID: 5094,
  contactIsBillingContact: null,
  contactIsPrimaryContact: null,
  contactJobTitle: "Superintendent ",
  contactMuncipality: null,
  contactMuncipalityID: null,
  contactName: "Jessica Allin",
  contactPhone: "519-521-0315",
  contactState: "Ontario",
  contactStateID: 7,
  contactStreetAddress: "2 International Boulevard, Suite 200",
  contactZip: "M9W 1A2",
  contactbtDelete: null,
  contactbtStatus: true,
  createdBy: null,
  createdDate: "2020-06-22T15:49:48.44",
  ext: "-",
  isAddressCopiedFromClient: true,
  modifiedBy: null,
  modifiedDate: null,
  quotesCount: 1,
  totalContacts: 1408} ,
  { activityDate: null,
    clientID: 3402,
    clientName: "thinc design",
    contactAddressID: null,
    contactCity: "Toronto",
    contactCountry: "Canada",
    contactCountryID: 1,
    contactEmail: "mtocher@thincdesign.ca",
    contactID: 5939,
    contactIsBillingContact: null,
    contactIsPrimaryContact: null,
    contactJobTitle: "Partner",
    contactMuncipality: null,
    contactMuncipalityID: null,
    contactName: "Mike Tocher",
    contactPhone: "416-236-3335",
    contactState: "Ontario",
    contactStateID: 7,
    contactStreetAddress: "171 East Liberty Street, Unit 266",
    contactZip: "M6K 3P6",
    contactbtDelete: null,
    contactbtStatus: true,
    createdBy: null,
    createdDate: "2020-07-13T09:03:44.47",
    ext: "302",
    isAddressCopiedFromClient: true,
    modifiedBy: null,
    modifiedDate: null,
    quotesCount: 1,
    totalContacts: 1408 },
    {
    activityDate: null,
    clientID: 3271,
    clientName: "Rohnbrad Inc.",
    contactAddressID: null,
    contactCity: "Guleph",
    contactCountry: "Canada",
    contactCountryID: 1,
    contactEmail: "johanna@ftarchitects.ca",
    contactID: 5335,
    contactIsBillingContact: null,
    contactIsPrimaryContact: null,
    contactJobTitle: "NA",
    contactMuncipality: null,
    contactMuncipalityID: null,
    contactName: "Bob Ireland",
    contactPhone: "000-000-0000",
    contactState: "Ontario",
    contactStateID: 7,
    contactStreetAddress: "174 Wyndham Street North, Suite 303",
    contactZip: "N1H 6R7",
    contactbtDelete: null,
    contactbtStatus: true,
    createdBy: null,
    createdDate: "2020-06-25T15:41:37.053",
    ext: "-",
    isAddressCopiedFromClient: true,
    modifiedBy: null,
    modifiedDate: null,
    quotesCount: 1,
    totalContacts: 1408 },
    {
    activityDate: null,
    clientID: 3237,
    clientName: "Northfield Development Corporation ",
    contactAddressID: null,
    contactCity: "NA",
    contactCountry: "Canada",
    contactCountryID: 1,
    contactEmail: "ashley@baxterengineering.ca",
    contactID: 5604,
    contactIsBillingContact: false,
    contactIsPrimaryContact: false,
    contactJobTitle: "NA",
    contactMuncipality: null,
    contactMuncipalityID: null,
    contactName: "Ashley Baxter ",
    contactPhone: "613-243-3166",
    contactState: "Ontario",
    contactStateID: 7,
    contactStreetAddress: "NA",
    contactZip: "NA",
    contactbtDelete: null,
    contactbtStatus: true,
    createdBy: null,
    createdDate: "2020-07-03T13:04:26.65",
    ext: "-",
    isAddressCopiedFromClient: false,
    modifiedBy: null,
    modifiedDate: null,
    quotesCount: 1,
    totalContacts: 1408 },
    {
    activityDate: null,
    clientID: 3230,
    clientName: "Ledcor Construction Limited",
    contactAddressID: null,
    contactCity: "Toronto",
    contactCountry: "Canada",
    contactCountryID: 1,
    contactEmail: "jessica.allin@ledcor.com",
    contactID: 5094,
    contactIsBillingContact: null,
    contactIsPrimaryContact: null,
    contactJobTitle: "Superintendent ",
    contactMuncipality: null,
    contactMuncipalityID: null,
    contactName: "Jessica Allin",
    contactPhone: "519-521-0315",
    contactState: "Ontario",
    contactStateID: 7,
    contactStreetAddress: "2 International Boulevard, Suite 200",
    contactZip: "M9W 1A2",
    contactbtDelete: null,
    contactbtStatus: true,
    createdBy: null,
    createdDate: "2020-06-22T15:49:48.44",
    ext: "-",
    isAddressCopiedFromClient: true,
    modifiedBy: null,
    modifiedDate: null,
    quotesCount: 1,
    totalContacts: 1408},
    { activityDate: null,
      clientID: 3402,
      clientName: "thinc design",
      contactAddressID: null,
      contactCity: "Toronto",
      contactCountry: "Canada",
      contactCountryID: 1,
      contactEmail: "mtocher@thincdesign.ca",
      contactID: 5939,
      contactIsBillingContact: null,
      contactIsPrimaryContact: null,
      contactJobTitle: "Partner",
      contactMuncipality: null,
      contactMuncipalityID: null,
      contactName: "Mike Tocher",
      contactPhone: "416-236-3335",
      contactState: "Ontario",
      contactStateID: 7,
      contactStreetAddress: "171 East Liberty Street, Unit 266",
      contactZip: "M6K 3P6",
      contactbtDelete: null,
      contactbtStatus: true,
      createdBy: null,
      createdDate: "2020-07-13T09:03:44.47",
      ext: "302",
      isAddressCopiedFromClient: true,
      modifiedBy: null,
      modifiedDate: null,
      quotesCount: 1,
      totalContacts: 1408 },
      {
      activityDate: null,
      clientID: 3271,
      clientName: "Rohnbrad Inc.",
      contactAddressID: null,
      contactCity: "Guleph",
      contactCountry: "Canada",
      contactCountryID: 1,
      contactEmail: "johanna@ftarchitects.ca",
      contactID: 5335,
      contactIsBillingContact: null,
      contactIsPrimaryContact: null,
      contactJobTitle: "NA",
      contactMuncipality: null,
      contactMuncipalityID: null,
      contactName: "Bob Ireland",
      contactPhone: "000-000-0000",
      contactState: "Ontario",
      contactStateID: 7,
      contactStreetAddress: "174 Wyndham Street North, Suite 303",
      contactZip: "N1H 6R7",
      contactbtDelete: null,
      contactbtStatus: true,
      createdBy: null,
      createdDate: "2020-06-25T15:41:37.053",
      ext: "-",
      isAddressCopiedFromClient: true,
      modifiedBy: null,
      modifiedDate: null,
      quotesCount: 1,
      totalContacts: 1408 },
      {
      activityDate: null,
      clientID: 3237,
      clientName: "Northfield Development Corporation ",
      contactAddressID: null,
      contactCity: "NA",
      contactCountry: "Canada",
      contactCountryID: 1,
      contactEmail: "ashley@baxterengineering.ca",
      contactID: 5604,
      contactIsBillingContact: false,
      contactIsPrimaryContact: false,
      contactJobTitle: "NA",
      contactMuncipality: null,
      contactMuncipalityID: null,
      contactName: "Ashley Baxter ",
      contactPhone: "613-243-3166",
      contactState: "Ontario",
      contactStateID: 7,
      contactStreetAddress: "NA",
      contactZip: "NA",
      contactbtDelete: null,
      contactbtStatus: true,
      createdBy: null,
      createdDate: "2020-07-03T13:04:26.65",
      ext: "-",
      isAddressCopiedFromClient: false,
      modifiedBy: null,
      modifiedDate: null,
      quotesCount: 1,
      totalContacts: 1408 },
      {
      activityDate: null,
      clientID: 3230,
      clientName: "Ledcor Construction Limited",
      contactAddressID: null,
      contactCity: "Toronto",
      contactCountry: "Canada",
      contactCountryID: 1,
      contactEmail: "jessica.allin@ledcor.com",
      contactID: 5094,
      contactIsBillingContact: null,
      contactIsPrimaryContact: null,
      contactJobTitle: "Superintendent ",
      contactMuncipality: null,
      contactMuncipalityID: null,
      contactName: "Jessica Allin",
      contactPhone: "519-521-0315",
      contactState: "Ontario",
      contactStateID: 7,
      contactStreetAddress: "2 International Boulevard, Suite 200",
      contactZip: "M9W 1A2",
      contactbtDelete: null,
      contactbtStatus: true,
      createdBy: null,
      createdDate: "2020-06-22T15:49:48.44",
      ext: "-",
      isAddressCopiedFromClient: true,
      modifiedBy: null,
      modifiedDate: null,
      quotesCount: 1,
      totalContacts: 1408}]
  constructor(public dialog: MatDialog) { }

  ngOnInit() {

  }
  
  openContactDialog(stat){
    let dialogRef = this.dialog.open(ContactDialogComponent, {
      data: stat,
      height: 'auto',
      width: '730px',
      autoFocus: false,
    });
    
    dialogRef.afterClosed().subscribe(prospects => {
      if(prospects == 'save') {
  
      }
    });
  }

  openDeleteDialog(assets) {
    let dialogRef = this.dialog.open(DeleteConfirmDialogComponent, {
      data: assets,
      height: 'auto',
      width: 'auto',
      autoFocus: false
    });
    
    dialogRef.afterClosed().subscribe(data => {
      if (data != null && data !== undefined) {
      }
    });
  }

  fliterSearch() {}
  clearFilters() {
    this.contactName.setValue([]);
    this.clientName.setValue([]);
    this.jobTitle.setValue([]);
    this.contactNumber.setValue([]);
    this.statu.setValue([]);
    this.status_filter = '';
  }
}
